domain_path: C:/FPGA-learning/HW4/Vitis_MicroBlaze/microblaze_platform/export/microblaze_platform/sw/standalone_microblaze_0
app_src_dir: C:\AMDDesignTools\2026.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
